---
title: "Clean bib file"
date: "`r Sys.Date()`"
author: "Gabriel Mateus Bernardo Harrington"
output:
  html_document:
    highlight: tango
    number_sections: yes
    theme: united
    toc: yes
    toc_float:
      collapsed: yes
    code_download: true
    code_folding: show
    df_print: paged
  pdf_document:
    toc: no
bibliography: /home/mateus/Documents/masterLib.bib
csl: /home/mateus/Documents/citation_styles/elsevier-vancouver.csl
link-citations: true
---

```{r, label='setup-options', include=FALSE}
knitr::opts_chunk$set(
  eval = TRUE, # eval code chunks
  echo = TRUE, # include source code
  #fig.width = 6, # set figure dims
  #fig.height = 6
  warning = FALSE, # exclude warnings
  message = FALSE, # exclude messages
  error = FALSE # exclude errors
)
```

This is a function to subset a bib file to references used in a .Rmd file

```{r, label='load-packages'}
library(stringr)

input_file = "proteomic_paper_2020-02-11.Rmd"
input_bib = "extras/masterLib.bib"
filter_emails = 2
output_bib = "test.bib"

```

```{r, label='clean-bib'}
clean_bib <- function(input_file, output_keys = "extras/used_bib_keys.txt",
                      filter_emails = 0){
    ## read in .Rmd file
    lines <- paste(readLines(input_file), collapse = "")
    ## regex to get unique references in file
    entries <- unique(str_match_all(lines, "@([a-zA-Z0-9_.-]+)[,\\. \\?\\!\\]\\;]")[[1]][, 2])

    ## filter out any emails in yaml
    if (filter_emails > 0) {
        entries <- entries[-(1:filter_emails)]
        ## entries <- entries[-(18:68)]
    }

    ## exclude R packages
    entries <- entries[grepl("_", entries)]

    writeLines(entries, output_keys)

  }
```

```{r, label='apply-function'}
## now call the function
clean_bib("proteomic_paper_2020-02-11.Rmd", filter_emails = 2)
```

```{bash, label='bash-script'}
## need to get keys from .Rmd file
## this isn't working right
# awk '/@[a-zA-Z0-9_.-]/,/[,\\. \\?\\!\\]\\;]/{print}' proteomic_paper_2020-02-11.Rmd

## example of extracting a reference given a key
# awk '/samuelsson_anti-inflammatory_2001/,/^$/' masterLib.bib

## script for subsetting bib file

rm extras/paper.bib

for i in $(cat extras/used_bib_keys.txt)
do
    sed -n "/$i/,/^$/p" extras/masterLib.bib >> extras/paper.bib
done

```
